name: Deploy to Azure Web App - az400-123456789-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D46DC6F28374B77B26EC0B744FF259E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45C5B5EA84AD4EE29A8DE5398BA7097C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA816E0ECD534BB3B9A91D5DD18501DA }}

      - name: Deploy to Azure Web App (staging slot)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'az400-123456789-main'
          slot-name: 'staging'
          package: '.'
